//////////////////////////////////////////////
// This file is autogenerated, DO NOT EDIT! //
//////////////////////////////////////////////

#include <stdint.h>

uint16_t rs_6_3_rom_lookup( uint16_t erasure_pattern, uint16_t survival_pattern  ) {
	uint16_t ret_val = 0;
	switch ( erasure_pattern & (uint16_t)0x01ffu ) {
		case 0b000000001u:
			switch ( survival_pattern & (uint16_t)0x01ffu ) {
			case 0b111111000u:
				ret_val = 0;
				break;
			case 0b111110100u:
				ret_val = 1;
				break;
			case 0b111101100u:
				ret_val = 2;
				break;
			case 0b111011100u:
				ret_val = 3;
				break;
			case 0b110111100u:
				ret_val = 4;
				break;
			case 0b101111100u:
				ret_val = 5;
				break;
			case 0b011111100u:
				ret_val = 6;
				break;
			case 0b111110010u:
				ret_val = 7;
				break;
			case 0b111101010u:
				ret_val = 8;
				break;
			case 0b111011010u:
				ret_val = 9;
				break;
			case 0b110111010u:
				ret_val = 10;
				break;
			case 0b101111010u:
				ret_val = 11;
				break;
			case 0b011111010u:
				ret_val = 12;
				break;
			case 0b111100110u:
				ret_val = 13;
				break;
			case 0b111010110u:
				ret_val = 14;
				break;
			case 0b110110110u:
				ret_val = 15;
				break;
			case 0b101110110u:
				ret_val = 16;
				break;
			case 0b011110110u:
				ret_val = 17;
				break;
			case 0b111001110u:
				ret_val = 18;
				break;
			case 0b110101110u:
				ret_val = 19;
				break;
			case 0b101101110u:
				ret_val = 20;
				break;
			case 0b011101110u:
				ret_val = 21;
				break;
			case 0b110011110u:
				ret_val = 22;
				break;
			case 0b101011110u:
				ret_val = 23;
				break;
			case 0b011011110u:
				ret_val = 24;
				break;
			case 0b100111110u:
				ret_val = 25;
				break;
			case 0b010111110u:
				ret_val = 26;
				break;
			case 0b001111110u:
				ret_val = 27;
				break;
			default:
				// Error
				#ifdef NO_SYCL
				printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				#endif // NO_SYCL
				ret_val = -1;
				break;
			}
			break;
		case 0b000000010u:
			switch ( survival_pattern & (uint16_t)0x01ffu ) {
			case 0b111111000u:
				ret_val = 28;
				break;
			case 0b111110100u:
				ret_val = 29;
				break;
			case 0b111101100u:
				ret_val = 30;
				break;
			case 0b111011100u:
				ret_val = 31;
				break;
			case 0b110111100u:
				ret_val = 32;
				break;
			case 0b101111100u:
				ret_val = 33;
				break;
			case 0b011111100u:
				ret_val = 34;
				break;
			case 0b111110001u:
				ret_val = 35;
				break;
			case 0b111101001u:
				ret_val = 36;
				break;
			case 0b111011001u:
				ret_val = 37;
				break;
			case 0b110111001u:
				ret_val = 38;
				break;
			case 0b101111001u:
				ret_val = 39;
				break;
			case 0b011111001u:
				ret_val = 40;
				break;
			case 0b111100101u:
				ret_val = 41;
				break;
			case 0b111010101u:
				ret_val = 42;
				break;
			case 0b110110101u:
				ret_val = 43;
				break;
			case 0b101110101u:
				ret_val = 44;
				break;
			case 0b011110101u:
				ret_val = 45;
				break;
			case 0b111001101u:
				ret_val = 46;
				break;
			case 0b110101101u:
				ret_val = 47;
				break;
			case 0b101101101u:
				ret_val = 48;
				break;
			case 0b011101101u:
				ret_val = 49;
				break;
			case 0b110011101u:
				ret_val = 50;
				break;
			case 0b101011101u:
				ret_val = 51;
				break;
			case 0b011011101u:
				ret_val = 52;
				break;
			case 0b100111101u:
				ret_val = 53;
				break;
			case 0b010111101u:
				ret_val = 54;
				break;
			case 0b001111101u:
				ret_val = 55;
				break;
			default:
				// Error
				#ifdef NO_SYCL
				printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				#endif // NO_SYCL
				ret_val = -1;
				break;
			}
			break;
		case 0b000000100u:
			switch ( survival_pattern & (uint16_t)0x01ffu ) {
			case 0b111111000u:
				ret_val = 56;
				break;
			case 0b111110010u:
				ret_val = 57;
				break;
			case 0b111101010u:
				ret_val = 58;
				break;
			case 0b111011010u:
				ret_val = 59;
				break;
			case 0b110111010u:
				ret_val = 60;
				break;
			case 0b101111010u:
				ret_val = 61;
				break;
			case 0b011111010u:
				ret_val = 62;
				break;
			case 0b111110001u:
				ret_val = 63;
				break;
			case 0b111101001u:
				ret_val = 64;
				break;
			case 0b111011001u:
				ret_val = 65;
				break;
			case 0b110111001u:
				ret_val = 66;
				break;
			case 0b101111001u:
				ret_val = 67;
				break;
			case 0b011111001u:
				ret_val = 68;
				break;
			case 0b111100011u:
				ret_val = 69;
				break;
			case 0b111010011u:
				ret_val = 70;
				break;
			case 0b110110011u:
				ret_val = 71;
				break;
			case 0b101110011u:
				ret_val = 72;
				break;
			case 0b011110011u:
				ret_val = 73;
				break;
			case 0b111001011u:
				ret_val = 74;
				break;
			case 0b110101011u:
				ret_val = 75;
				break;
			case 0b101101011u:
				ret_val = 76;
				break;
			case 0b011101011u:
				ret_val = 77;
				break;
			case 0b110011011u:
				ret_val = 78;
				break;
			case 0b101011011u:
				ret_val = 79;
				break;
			case 0b011011011u:
				ret_val = 80;
				break;
			case 0b100111011u:
				ret_val = 81;
				break;
			case 0b010111011u:
				ret_val = 82;
				break;
			case 0b001111011u:
				ret_val = 83;
				break;
			default:
				// Error
				#ifdef NO_SYCL
				printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				#endif // NO_SYCL
				ret_val = -1;
				break;
			}
			break;
		case 0b000001000u:
			switch ( survival_pattern & (uint16_t)0x01ffu ) {
			case 0b111110100u:
				ret_val = 84;
				break;
			case 0b111110010u:
				ret_val = 85;
				break;
			case 0b111100110u:
				ret_val = 86;
				break;
			case 0b111010110u:
				ret_val = 87;
				break;
			case 0b110110110u:
				ret_val = 88;
				break;
			case 0b101110110u:
				ret_val = 89;
				break;
			case 0b011110110u:
				ret_val = 90;
				break;
			case 0b111110001u:
				ret_val = 91;
				break;
			case 0b111100101u:
				ret_val = 92;
				break;
			case 0b111010101u:
				ret_val = 93;
				break;
			case 0b110110101u:
				ret_val = 94;
				break;
			case 0b101110101u:
				ret_val = 95;
				break;
			case 0b011110101u:
				ret_val = 96;
				break;
			case 0b111100011u:
				ret_val = 97;
				break;
			case 0b111010011u:
				ret_val = 98;
				break;
			case 0b110110011u:
				ret_val = 99;
				break;
			case 0b101110011u:
				ret_val = 100;
				break;
			case 0b011110011u:
				ret_val = 101;
				break;
			case 0b111000111u:
				ret_val = 102;
				break;
			case 0b110100111u:
				ret_val = 103;
				break;
			case 0b101100111u:
				ret_val = 104;
				break;
			case 0b011100111u:
				ret_val = 105;
				break;
			case 0b110010111u:
				ret_val = 106;
				break;
			case 0b101010111u:
				ret_val = 107;
				break;
			case 0b011010111u:
				ret_val = 108;
				break;
			case 0b100110111u:
				ret_val = 109;
				break;
			case 0b010110111u:
				ret_val = 110;
				break;
			case 0b001110111u:
				ret_val = 111;
				break;
			default:
				// Error
				#ifdef NO_SYCL
				printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				#endif // NO_SYCL
				ret_val = -1;
				break;
			}
			break;
		case 0b000010000u:
			switch ( survival_pattern & (uint16_t)0x01ffu ) {
			case 0b111101100u:
				ret_val = 112;
				break;
			case 0b111101010u:
				ret_val = 113;
				break;
			case 0b111100110u:
				ret_val = 114;
				break;
			case 0b111001110u:
				ret_val = 115;
				break;
			case 0b110101110u:
				ret_val = 116;
				break;
			case 0b101101110u:
				ret_val = 117;
				break;
			case 0b011101110u:
				ret_val = 118;
				break;
			case 0b111101001u:
				ret_val = 119;
				break;
			case 0b111100101u:
				ret_val = 120;
				break;
			case 0b111001101u:
				ret_val = 121;
				break;
			case 0b110101101u:
				ret_val = 122;
				break;
			case 0b101101101u:
				ret_val = 123;
				break;
			case 0b011101101u:
				ret_val = 124;
				break;
			case 0b111100011u:
				ret_val = 125;
				break;
			case 0b111001011u:
				ret_val = 126;
				break;
			case 0b110101011u:
				ret_val = 127;
				break;
			case 0b101101011u:
				ret_val = 128;
				break;
			case 0b011101011u:
				ret_val = 129;
				break;
			case 0b111000111u:
				ret_val = 130;
				break;
			case 0b110100111u:
				ret_val = 131;
				break;
			case 0b101100111u:
				ret_val = 132;
				break;
			case 0b011100111u:
				ret_val = 133;
				break;
			case 0b110001111u:
				ret_val = 134;
				break;
			case 0b101001111u:
				ret_val = 135;
				break;
			case 0b011001111u:
				ret_val = 136;
				break;
			case 0b100101111u:
				ret_val = 137;
				break;
			case 0b010101111u:
				ret_val = 138;
				break;
			case 0b001101111u:
				ret_val = 139;
				break;
			default:
				// Error
				#ifdef NO_SYCL
				printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				#endif // NO_SYCL
				ret_val = -1;
				break;
			}
			break;
		case 0b000100000u:
			switch ( survival_pattern & (uint16_t)0x01ffu ) {
			case 0b111011100u:
				ret_val = 140;
				break;
			case 0b111011010u:
				ret_val = 141;
				break;
			case 0b111010110u:
				ret_val = 142;
				break;
			case 0b111001110u:
				ret_val = 143;
				break;
			case 0b110011110u:
				ret_val = 144;
				break;
			case 0b101011110u:
				ret_val = 145;
				break;
			case 0b011011110u:
				ret_val = 146;
				break;
			case 0b111011001u:
				ret_val = 147;
				break;
			case 0b111010101u:
				ret_val = 148;
				break;
			case 0b111001101u:
				ret_val = 149;
				break;
			case 0b110011101u:
				ret_val = 150;
				break;
			case 0b101011101u:
				ret_val = 151;
				break;
			case 0b011011101u:
				ret_val = 152;
				break;
			case 0b111010011u:
				ret_val = 153;
				break;
			case 0b111001011u:
				ret_val = 154;
				break;
			case 0b110011011u:
				ret_val = 155;
				break;
			case 0b101011011u:
				ret_val = 156;
				break;
			case 0b011011011u:
				ret_val = 157;
				break;
			case 0b111000111u:
				ret_val = 158;
				break;
			case 0b110010111u:
				ret_val = 159;
				break;
			case 0b101010111u:
				ret_val = 160;
				break;
			case 0b011010111u:
				ret_val = 161;
				break;
			case 0b110001111u:
				ret_val = 162;
				break;
			case 0b101001111u:
				ret_val = 163;
				break;
			case 0b011001111u:
				ret_val = 164;
				break;
			case 0b100011111u:
				ret_val = 165;
				break;
			case 0b010011111u:
				ret_val = 166;
				break;
			case 0b001011111u:
				ret_val = 167;
				break;
			default:
				// Error
				#ifdef NO_SYCL
				printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				#endif // NO_SYCL
				ret_val = -1;
				break;
			}
			break;
		case 0b001000000u:
			switch ( survival_pattern & (uint16_t)0x01ffu ) {
			case 0b110111100u:
				ret_val = 168;
				break;
			case 0b110111010u:
				ret_val = 169;
				break;
			case 0b110110110u:
				ret_val = 170;
				break;
			case 0b110101110u:
				ret_val = 171;
				break;
			case 0b110011110u:
				ret_val = 172;
				break;
			case 0b100111110u:
				ret_val = 173;
				break;
			case 0b010111110u:
				ret_val = 174;
				break;
			case 0b110111001u:
				ret_val = 175;
				break;
			case 0b110110101u:
				ret_val = 176;
				break;
			case 0b110101101u:
				ret_val = 177;
				break;
			case 0b110011101u:
				ret_val = 178;
				break;
			case 0b100111101u:
				ret_val = 179;
				break;
			case 0b010111101u:
				ret_val = 180;
				break;
			case 0b110110011u:
				ret_val = 181;
				break;
			case 0b110101011u:
				ret_val = 182;
				break;
			case 0b110011011u:
				ret_val = 183;
				break;
			case 0b100111011u:
				ret_val = 184;
				break;
			case 0b010111011u:
				ret_val = 185;
				break;
			case 0b110100111u:
				ret_val = 186;
				break;
			case 0b110010111u:
				ret_val = 187;
				break;
			case 0b100110111u:
				ret_val = 188;
				break;
			case 0b010110111u:
				ret_val = 189;
				break;
			case 0b110001111u:
				ret_val = 190;
				break;
			case 0b100101111u:
				ret_val = 191;
				break;
			case 0b010101111u:
				ret_val = 192;
				break;
			case 0b100011111u:
				ret_val = 193;
				break;
			case 0b010011111u:
				ret_val = 194;
				break;
			case 0b000111111u:
				ret_val = 195;
				break;
			default:
				// Error
				#ifdef NO_SYCL
				printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				#endif // NO_SYCL
				ret_val = -1;
				break;
			}
			break;
		case 0b010000000u:
			switch ( survival_pattern & (uint16_t)0x01ffu ) {
			case 0b101111100u:
				ret_val = 196;
				break;
			case 0b101111010u:
				ret_val = 197;
				break;
			case 0b101110110u:
				ret_val = 198;
				break;
			case 0b101101110u:
				ret_val = 199;
				break;
			case 0b101011110u:
				ret_val = 200;
				break;
			case 0b100111110u:
				ret_val = 201;
				break;
			case 0b001111110u:
				ret_val = 202;
				break;
			case 0b101111001u:
				ret_val = 203;
				break;
			case 0b101110101u:
				ret_val = 204;
				break;
			case 0b101101101u:
				ret_val = 205;
				break;
			case 0b101011101u:
				ret_val = 206;
				break;
			case 0b100111101u:
				ret_val = 207;
				break;
			case 0b001111101u:
				ret_val = 208;
				break;
			case 0b101110011u:
				ret_val = 209;
				break;
			case 0b101101011u:
				ret_val = 210;
				break;
			case 0b101011011u:
				ret_val = 211;
				break;
			case 0b100111011u:
				ret_val = 212;
				break;
			case 0b001111011u:
				ret_val = 213;
				break;
			case 0b101100111u:
				ret_val = 214;
				break;
			case 0b101010111u:
				ret_val = 215;
				break;
			case 0b100110111u:
				ret_val = 216;
				break;
			case 0b001110111u:
				ret_val = 217;
				break;
			case 0b101001111u:
				ret_val = 218;
				break;
			case 0b100101111u:
				ret_val = 219;
				break;
			case 0b001101111u:
				ret_val = 220;
				break;
			case 0b100011111u:
				ret_val = 221;
				break;
			case 0b001011111u:
				ret_val = 222;
				break;
			case 0b000111111u:
				ret_val = 223;
				break;
			default:
				// Error
				#ifdef NO_SYCL
				printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				#endif // NO_SYCL
				ret_val = -1;
				break;
			}
			break;
		case 0b100000000u:
			switch ( survival_pattern & (uint16_t)0x01ffu ) {
			case 0b011111100u:
				ret_val = 224;
				break;
			case 0b011111010u:
				ret_val = 225;
				break;
			case 0b011110110u:
				ret_val = 226;
				break;
			case 0b011101110u:
				ret_val = 227;
				break;
			case 0b011011110u:
				ret_val = 228;
				break;
			case 0b010111110u:
				ret_val = 229;
				break;
			case 0b001111110u:
				ret_val = 230;
				break;
			case 0b011111001u:
				ret_val = 231;
				break;
			case 0b011110101u:
				ret_val = 232;
				break;
			case 0b011101101u:
				ret_val = 233;
				break;
			case 0b011011101u:
				ret_val = 234;
				break;
			case 0b010111101u:
				ret_val = 235;
				break;
			case 0b001111101u:
				ret_val = 236;
				break;
			case 0b011110011u:
				ret_val = 237;
				break;
			case 0b011101011u:
				ret_val = 238;
				break;
			case 0b011011011u:
				ret_val = 239;
				break;
			case 0b010111011u:
				ret_val = 240;
				break;
			case 0b001111011u:
				ret_val = 241;
				break;
			case 0b011100111u:
				ret_val = 242;
				break;
			case 0b011010111u:
				ret_val = 243;
				break;
			case 0b010110111u:
				ret_val = 244;
				break;
			case 0b001110111u:
				ret_val = 245;
				break;
			case 0b011001111u:
				ret_val = 246;
				break;
			case 0b010101111u:
				ret_val = 247;
				break;
			case 0b001101111u:
				ret_val = 248;
				break;
			case 0b010011111u:
				ret_val = 249;
				break;
			case 0b001011111u:
				ret_val = 250;
				break;
			case 0b000111111u:
				ret_val = 251;
				break;
			default:
				// Error
				#ifdef NO_SYCL
				printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				#endif // NO_SYCL
				ret_val = -1;
				break;
			}
			break;
	default:
		// Error
				#ifdef NO_SYCL
		printf("%s:%d ERROR: Unsupported erasure pattern 0x%04x\n", __FILE__, __LINE__, erasure_pattern);
				#endif // NO_SYCL
		ret_val = -1;
	break;
	}
	
	return ret_val;
}
