/**********************************************************************
* This file is autogenerated, DO NOT EDIT!
**********************************************************************/

#include <stdint.h>

uint16_t rs_3_2_rom_lookup( uint16_t erasure_pattern, uint16_t survival_pattern  ) {
	uint16_t ret_val = 0;
	switch ( erasure_pattern & (uint16_t)0x001fu ) {
		case 0b00001u:
			switch ( survival_pattern & (uint16_t)0x001fu ) {
			case 0b11100u:
				ret_val = 0;
				break;
			case 0b11010u:
				ret_val = 1;
				break;
			case 0b10110u:
				ret_val = 2;
				break;
			case 0b01110u:
				ret_val = 3;
				break;
			default:
				// Error
				// printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				ret_val = -1;
				break;
			}
			break;
		case 0b00010u:
			switch ( survival_pattern & (uint16_t)0x001fu ) {
			case 0b11100u:
				ret_val = 4;
				break;
			case 0b11001u:
				ret_val = 5;
				break;
			case 0b10101u:
				ret_val = 6;
				break;
			case 0b01101u:
				ret_val = 7;
				break;
			default:
				// Error
				// printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				ret_val = -1;
				break;
			}
			break;
		case 0b00100u:
			switch ( survival_pattern & (uint16_t)0x001fu ) {
			case 0b11010u:
				ret_val = 8;
				break;
			case 0b11001u:
				ret_val = 9;
				break;
			case 0b10011u:
				ret_val = 10;
				break;
			case 0b01011u:
				ret_val = 11;
				break;
			default:
				// Error
				// printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				ret_val = -1;
				break;
			}
			break;
		case 0b01000u:
			switch ( survival_pattern & (uint16_t)0x001fu ) {
			case 0b10110u:
				ret_val = 12;
				break;
			case 0b10101u:
				ret_val = 13;
				break;
			case 0b10011u:
				ret_val = 14;
				break;
			case 0b00111u:
				ret_val = 15;
				break;
			default:
				// Error
				// printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				ret_val = -1;
				break;
			}
			break;
		case 0b10000u:
			switch ( survival_pattern & (uint16_t)0x001fu ) {
			case 0b01110u:
				ret_val = 16;
				break;
			case 0b01101u:
				ret_val = 17;
				break;
			case 0b01011u:
				ret_val = 18;
				break;
			case 0b00111u:
				ret_val = 19;
				break;
			default:
				// Error
				// printf("%s:%d ERROR: Unsupported survival pattern 0x%04x\n", __FILE__, __LINE__, survival_pattern);
				ret_val = -1;
				break;
			}
			break;
	default:
		// Error
		// printf("%s:%d ERROR: Unsupported erasure pattern 0x%04x\n", __FILE__, __LINE__, erasure_pattern);
		ret_val = -1;
	break;
	}
	
	return ret_val;
}
