#!/bin/bash
# NOTE: the AFU flow requires a relocatable PR-tree to be generated by the FIM build

#############
# Build AFU #
#############
cd $OFS_ROOTDIR/work_x16_adp

BUILD_SYNTH_DIR=$PWD/host_chan_mmio_synth
afu_synth_setup     \
    --sources $OFS_PLATFORM_AFU_BBB/plat_if_tests/host_chan_mmio/hw/rtl/test_mmio_axi1.txt \
    ${BUILD_SYNTH_DIR} 
if [ $? -ne 0 ]; then
    echo '[ERROR] Could not setup synthesis directory.' ; return;
fi

cd ${BUILD_SYNTH_DIR} 

echo "[INFO] Start compilation of full AF bitstream..."
$OFS_ROOTDIR/work_x16_adp/pr_build_template/bin/afu_synth
# Check for exit code
if [ $? -ne 0 ]; then
    echo '[ERROR] Compilation failed.' ; return;
fi
# Check for output file
if [ ! -e *.gbs ]; then
    echo '[ERROR] Cannot find GBS.' ; return;
fi
