#ifndef __SYCL_REGISTER_MAP_OFFSET_H__
#define __SYCL_REGISTER_MAP_OFFSET_H__

#define AFU_DFH_REG     0x0
#define AFU_ID_LO       0x8
#define AFU_ID_HI       0x10
#define AFU_NEXT        0x18
#define AFU_RESERVED    0x20

#define KERNEL_STATUS                   ZTS11RSERASUREID_REGISTER_MAP_STATUS_REG
#define KERNEL_START                    (0x8 + ZTS11RSERASUREID_REGISTER_MAP_OFFSET)
#define KERNEL_START_VALUE              ((uint64_t)1u)
#define KERNEL_ARG_DEVICE_READ_REG      ZTS11RSERASUREID_REGISTER_MAP_ARG_ARG_DEVICE_READ_REG
#define KERNEL_ARG_DEVICE_WRITE_REG     ZTS11RSERASUREID_REGISTER_MAP_ARG_ARG_DEVICE_WRITE_REG
#define KERNEL_ARG_RS_ERASURE_CSR_REG   ZTS11RSERASUREID_REGISTER_MAP_ARG_ARG_RS_ERASURE_CSR_REG

#endif // __SYCL_REGISTER_MAP_OFFSET_H__
