#ifndef __SYCL_REGISTER_MAP_OFFSET_H__
#define __SYCL_REGISTER_MAP_OFFSET_H__

// Register map emitted by SYCL
#include "register_map_offsets.hpp"

#define AFU_DFH_REG     0x0
#define AFU_ID_LO       0x8
#define AFU_ID_HI       0x10
#define AFU_NEXT        0x18
#define AFU_RESERVED    0x20

// Addresses
#define KERNEL_STATUS                   (ZTS14SYCLLOOPBACKID_REGISTER_MAP_STATUS_REG)
#define KERNEL_START                    (0x8 + ZTS14SYCLLOOPBACKID_REGISTER_MAP_OFFSET) // Don't read in ASE!
#define KERNEL_FINISH_COUNTER           (ZTS14SYCLLOOPBACKID_REGISTER_MAP_FINISHCOUNTER_REG)
#define KERNEL_ARG_DEVICE_READ_REG      (ZTS14SYCLLOOPBACKID_REGISTER_MAP_ARG_ARG_DEVICE_READ_REG)
#define KERNEL_ARG_DEVICE_WRITE_REG     (ZTS14SYCLLOOPBACKID_REGISTER_MAP_ARG_ARG_DEVICE_WRITE_REG)
#define KERNEL_ARG_RS_LENGTH_LINES_REG  (ZTS14SYCLLOOPBACKID_REGISTER_MAP_ARG_ARG_LENGTH_LINES_REG)

// Values
#define KERNEL_START_VALUE              ((uint32_t)1u) // This must be 32-bits

#endif // __SYCL_REGISTER_MAP_OFFSET_H__
