#!/bin/bash
# NOTE: the AFU flow requires a relocatable PR-tree to be generated by the FIM build

####################
# Setup enviroment #
####################
source settings_ase.sh

#############
# Setup ASE #
#############

cd $OFS_ROOTDIR/work_x16_adp

BUILD_SIM_DIR=$PWD/host_chan_mmio_sim
afu_sim_setup \
    --sources $OFS_PLATFORM_AFU_BBB/plat_if_tests/host_chan_mmio/hw/rtl/test_mmio_axi1.txt 
    --tool QUESTA \
    $BUILD_SIM_DIR

cd host_chan_mmio_sim
make
make sim

# NOTE: now in anther shell source afu_ase_sw.sh

echo "You can now inspect the waves with:"
echo "  make wave"