#!/bin/bash
# NOTE: the AFU flow requires a relocatable PR-tree to be generated by the FIM build

####################
# Setup enviroment #
####################
source settings_ase.sh
export ASE_WORKDIR=<path to running ASE>

##########################
# Build and run software #
##########################
cd $OFS_PLATFORM_AFU_BBB/plat_if_tests/host_chan_mmio/sw  
make # old OPAE required ASE=1
with_ase ./host_chan_mmio